Empty print statement caused compile time error
Gfortran 11.3.0 says: 

   94 |         print*,
      |               1
Error: Comma after * at (1) not allowed without I/O list

Can be fixed by either printing a space, for skipping a line, or removing the entire print statement. Suggested fix is printing a space.